RegisterNetEvent("RollDownWindow")
AddEventHandler("RollDownWindow", function(toggle)
function RollDownWindow(commandEntered, vehicle, playerPed)
    RollDownWindow(GetVehiclePedIsIn(GetPlayerPed(-1)), 1)
end)
